local Short = dofile("APIS/ShortCuts.lua")
print("Enter your SecretPass to encrypt it:")
local realPass = read("*")
Short.Write(realPass, "RangerBankData/SecretPass.txt")
print("Success! Now SecretPass is encrypted!.")
